### ISSUE TITLE
Render Xournal++ document inside Obsidian

### ISSUE THREAD

**Issue by MathisP75** [gabrielrueda/obsidian-xournal-integration-plugin#4]
I have no idea how easy this would be to implement or if it's even possible, but it would be an awesome feature.

**Comment by gabrielrueda** [comment]
@MathisP75 
I think this is a great idea, and was my original vision for this. But, I went for PDF embedding since it was easier to implement.

I have looked a bit into this in the past. Basically obsidian uses an XML format to save content. I believe you can also render XML as if it were an HTML page on obsidian. However, I don't know if the XML on xournal will be a 1 on 1 translation for HTML XML.

I can create a branch for you if you want to develop this idea, as well as provide assistance.

You can read more about the xournal format here:
https://math.mit.edu/~auroux/software/xournal/manual.html#file-format
https://github.com/xournalpp/xournalpp/issues/2204#issuecomment-862774433

**Comment by MathisP75** [comment]
Thank you, good to know! I doubt I have the knowledge to do that, so don't bother making a branch for it.

**Comment by gabrielrueda** [comment]
Checklist for this Feature:

### Image
- [x] Basic Support -> image data is transferred
- [x] Change width and height  to actually width and height (need to calculate with bottom and right coordinates)

### Text
- [x] Support
- [x] Support for attributes for color and fonts
- [x] issue: text rendering is too high

### Lines (strokes or paths -> anything handrawn)
- [x] Basic Support
- [x] Colors
- [X ] Fixed Line Width
- [x] Highlighter
 

### Multiple Pages
- [x] Just one embedded file for all pages seems to work
- [x] support for different sized pages

### PDF Inside rendering
- [ ] Create fallback to just show PDF

### Layers
- i don't use this feature, but want to try implementing it -> low priority 

Check out the render-inside-obsidian branch for progress on this.
